language: python
python:
- '3.5'
script:
- mkdir .build/
- git clone https://github.com/TheMysteriousVincent/sqf.git .build/sqf
- python3 .build/sqf/sqflint.py -d addons/
- python3 tools/config_style_checker.py
notification:
  email:
    on_success: never
    on_failure: change
